signing_key_password=talangraga165
signing_keystore_password=talangraga165
signing_key_alias=talangraga
signing_key_location=../keystore/talangraga_keystore.jks

# URL
stagingUrl=http://127.0.0.1:8000/
productionUrl=http://27.112.78.97:8000/

# Kotzilla
kotzillaStagingKey=ktz-sdk-DZMH3UFugdk5m6UV2gMBr876g8uoFkhPBFb1A28lojM
kotzillaProductionKey=ktz-sdk-nO-XzT4ULQfLeuf4f3PYTCRGtGYmJHtvP3_D4S_v078
